# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PjMactop < Formula
  desc "Apple Silicon Monitor Top written in Go Lang"
  homepage "https://github.com/purplejay-io/mactop"
  version "0.0.2"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/purplejay-io/mactop/releases/download/0.0.2/pj-mactop_0.0.2_darwin_arm64.tar.gz"
    sha256 "52604b20383a63376b93a1925fb66c2fce49463ad7adde2141c08ef0306a14d6"

    def install
      bin.install "pj-mactop"
    end
  end

  def caveats
    <<~EOS
      mactop requires macOS 12+, and runs only on Apple Silicon.
    EOS
  end
end
